ci:
  upload:
    target: temporary-public-storage
  collect:
    isSinglePageApplication: true
    staticDistDir: dist
    url:
      - http://localhost/
      - http://localhost/content
      - http://localhost/about
      - http://localhost/notfound
      - http://localhost/projects
  assert:
    preset: lighthouse:recommended
    assertions:
<<<<<<< HEAD
      csp-xss: off
      image-size-responsive: off
      maskable-icon: off
      service-worker: off
      unsized-images: off
      unused-javascript: off
      uses-responsive-images: off
      preload-lcp-image: off
=======
      csp-xss: warn
      heading-order: warn
      image-size-responsive: warn
      maskable-icon: warn
      service-worker: warn
      unsized-images: warn
      unused-javascript: warn
      uses-responsive-images: warn
      preload-lcp-image: warn
>>>>>>> 417c1bf (fix meta-description lighthouse)
