ci:
  upload:
    target: temporary-public-storage
  collect:
    isSinglePageApplication: true
    staticDistDir: dist
    url:
      - http://localhost/
      - http://localhost/content
      - http://localhost/about
      - http://localhost/notfound
      - http://localhost/projects
  assert:
    preset: lighthouse:recommended
    assertions:
      csp-xss: off
      heading-order: off
      image-size-responsive: off
      link-text: off
      maskable-icon: off
      meta-description: off
      service-worker: off
      unsized-images: off
      unused-javascript: off
      uses-responsive-images: off
      preload-lcp-image: off
