ci:
  upload:
    target: temporary-public-storage
  collect:
    isSinglePageApplication: true
    staticDistDir: out
    url:
      - http://localhost/
      - http://localhost/content.html
      - http://localhost/about.html
      - http://localhost/404.html
      - http://localhost/projects.html
      - http://localhost/privacy.html
  assert:
    preset: lighthouse:recommended
    assertions:
      categories:performance:
        - error
        - minScore: 0.9
      categories:accessibility:
        - error
        - minScore: 1
      categories:best-practices:
        - error
        - minScore: 1
      categories:seo:
        - error
        - minScore: 1

      # requires CSP in a header, which is not possible on gh-pages
      csp-xss: off
      # handled by NextJS
      unsized-images: off

      maskable-icon: warn
      service-worker: warn
