ci:
  upload:
    target: temporary-public-storage
  collect:
    isSinglePageApplication: true
    staticDistDir: /dist
    url:
      - http://localhost/
      - http://localhost/content
      - http://localhost/about
      - http://localhost/notfound
      - http://localhost/projects
  assert:
    preset: lighthouse:recommended
