ci:
  upload:
    target: temporary-public-storage
  collect:
    isSinglePageApplication: true
    staticDistDir: dist
    url:
      - http://localhost/
      - http://localhost/content
      - http://localhost/about
      - http://localhost/notfound
      - http://localhost/projects
  assert:
    preset: lighthouse:recommended
    assertions:
      categories:performance:
        - error
        - minScore: 0.8
      categories:accessibility:
        - error
        - minScore: 1
      categories:best-practices:
        - error
        - minScore: 1
      categories:seo:
        - error
        - minScore: 1
      cumulative-layout-shift:
        - error
        - maxNumericValue: 0.1
      # requires CSP in a header, which is not possible on gh-pages
      csp-xss: warn

      image-size-responsive: warn
      maskable-icon: warn
      service-worker: warn
      unused-javascript: warn
      uses-responsive-images: warn
