ci:
  upload:
    target: temporary-public-storage
  collect:
    isSinglePageApplication: true
    staticDistDir: dist
    url:
      - http://localhost/
      - http://localhost/content
      - http://localhost/about
      - http://localhost/notfound
      - http://localhost/projects
  assert:
    preset: lighthouse:recommended
    assertions:
      # requires CSP in a header, which is not possible on gh-pages
      csp-xss: warn

      image-size-responsive: warn
      maskable-icon: warn
      service-worker: warn
      unsized-images: warn
      unused-javascript: warn
      uses-responsive-images: warn
