name: CI
on:
  push:
    branches-ignore:
      - main
      - gh-pages
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
      - name: install npm packages
        run: npm ci
      - name: check for outdated dependencies
        run: npm run deps
      - name: format
        run: npm run checkformat
      - name: lint
        run: npm run checklint
      - name: build
        run: npm run build
      - name: lighthouse desktop
        run: npx lhci autorun --collect.settings.preset=desktop
      - name: lighthouse mobile
        run: npx lhci autorun
