name: CI/CD
on: [push]
jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
      - name: install npm packages
        run: npm ci
      - name: check for outdated dependencies
        run: npm run deps
        if: github.ref_name != 'main'
      - name: format
        run: npm run checkformat
      - name: lint
        run: npm run checklint
      - name: build
        run: npm run build
      - name: lighthouse desktop
        run: npx lhci autorun --collect.settings.preset=desktop
      - name: lighthouse mobile
        run: npx lhci autorun
      - name: deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref_name == 'main'
